name       : pigz
version    : 2.3.3
release    : 1
source     :
    - http://zlib.net/pigz/pigz-2.3.3.tar.gz : 4e8b67b432ce7907575a549f3e1cac4709781ba0f6b48afea9f59369846b509c
license    : Apache-2.0
summary    : Parallel gzip
description: |
    pigz, which stands for parallel implementation of gzip, is a fully functional replacement for gzip that exploits multiple processors and multiple cores to the hilt when compressing data. pigz was written by Mark Adler, and uses the zlib and pthread libraries.
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-we-link-correctly.patch
build      : |
    %make CFLAGS="${CFLAGS}" LDFLAGS="${LDFLAGS}"
install    : |
    install -D -m 00755 pigz $installdir/usr/bin/pigz
    install -D -m 00755 unpigz $installdir/usr/bin/unpigz
