name       : pigz
version    : '2.6'
release    : 4
source     :
    - https://github.com/madler/pigz/archive/refs/tags/v2.6.tar.gz : 577673676cd5c7219f94b236075451220bae3e1ca451cf849947a2998fbf5820
license    : Apache-2.0
component  : system.utils
homepage   : https://zlib.net/pigz/
summary    : Parallel implementation of gzip
description: |
    pigz, which stands for parallel implementation of gzip, is a fully functional replacement for gzip that exploits multiple processors and multiple cores to the hilt when compressing data. pigz was written by Mark Adler, and uses the zlib and pthread libraries.
build      : |
    %make CFLAGS="${CFLAGS}" LDFLAGS="${LDFLAGS}"
install    : |
    install -Dm 00755 pigz $installdir/usr/bin/pigz
    install -Dm 00755 unpigz $installdir/usr/bin/unpigz
    install -Dm 00644 pigz.1 $installdir/usr/share/man/man1/pigz.1
