name       : pigz
version    : '2.4'
release    : 2
source     :
    - https://github.com/madler/pigz/archive/v2.4.tar.gz : e228e7d18b34c4ece8d596eb6eee97bde533c6beedbb728d07d3abe90b4b1b52
license    : Apache-2.0
component  : system.utils
summary    : Parallel gzip
description: |
    pigz, which stands for parallel implementation of gzip, is a fully functional replacement for gzip that exploits multiple processors and multiple cores to the hilt when compressing data. pigz was written by Mark Adler, and uses the zlib and pthread libraries.
build      : |
    %make CFLAGS="${CFLAGS}" LDFLAGS="${LDFLAGS}"
install    : |
    install -D -m 00755 pigz $installdir/usr/bin/pigz
    install -D -m 00755 unpigz $installdir/usr/bin/unpigz
