name       : pigz
version    : '2.8'
release    : 6
source     :
    - https://zlib.net/pigz/pigz-2.8.tar.gz : eb872b4f0e1f0ebe59c9f7bd8c506c4204893ba6a8492de31df416f0d5170fd0
license    : Apache-2.0
component  : system.utils
homepage   : https://zlib.net/pigz/
summary    : Parallel implementation of gzip
description: |
    pigz, which stands for parallel implementation of gzip, is a fully functional replacement for gzip that exploits multiple processors and multiple cores to the hilt when compressing data. pigz was written by Mark Adler, and uses the zlib and pthread libraries.
build      : |
    %make CFLAGS="${CFLAGS}" LDFLAGS="${LDFLAGS}"
install    : |
    install -Dm 00755 pigz $installdir/usr/bin/pigz
    install -Dm 00755 unpigz $installdir/usr/bin/unpigz
    install -Dm 00644 pigz.1 $installdir/usr/share/man/man1/pigz.1
